businesses/urls.py
from django.conf.urls import url
from businesses import views

urlpatterns = [
	url(r'^create/$', views.business_create, name="create"),
	url(r'^detail/(?P<business_slug>[-\w]+)/$', views.business_detail, name="detail"),
	url(r'^list/$', views.business_list, name="list"),
	url(r'^update/(?P<business_slug>[-\w]+)/$', views.business_update, name="update"),
	url(r'^delete/(?P<business_slug>[-\w]+)/$', views.business_delete, name="delete"),
	url(r'^signup/$', views.usersignup, name="signup"),
	url(r'^login/$', views.userlogin, name="login"),
	url(r'^logout/$', views.userlogout, name="logout"),
	]

small_businesses/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
url(r'^admin/', admin.site.urls),
url(r'^businesses/', include('businesses.urls', namespace="businesses")),

url(r'^comments/', include('django_comments.urls')),

]
if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

businesses/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Business(models.Model):
	author = models.ForeignKey(User, default=1)
	title = models.CharField(max_length=255)
	slug = models.SlugField(null=True)
	image = models.ImageField(null=True, blank=True, upload_to="business_images")
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	updated = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ["-timestamp", "-updated"]

	class Like(models.Model):
    	user = models.ForeignKey(User)
    	post = models.ForeignKey(Post)
    	created = models.DateTimeField(auto_now_add=True)
    	
	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("businesses:detail", kwargs={"business_slug": self.slug})

def create_slug(instance, new_slug=None):
	slug = slugify (instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Business.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s"%(slug,qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

def pre_save_post_reciever(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug=create_slug(instance)

	pre_save.connect(pre_save_post_reciever,sender=Business)			

# Create your models here.

businesses/forms.py
from django import forms
from .models import Business
from django.contrib.auth.models import User

class BusinessForm(forms.ModelForm):
	class Meta:
		model = Business
		fields = ['title', 'content', 'image', 'draft', 'publish']

		widgets={
		'publish': forms.DateInput(attrs={"type":"date"}),
		}

class UserSignup(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','password']

        widgets={
        'password': forms.PasswordInput(),
        }

class UserLogin(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput())		

businesses/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
from .models import Business 
from .forms import BusinessForm
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib.parse import quote
from django.http import Http404
from django.utils import timezone
from django.db.models import Q
from .forms import UserSignup, UserLogin
from django.contrib.auth import authenticate, login, logout


def business_create(request):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	form = BusinessForm(request.BUSINESS or None)
	if form.is_valid():
		business = form.save(commit = False)
		business.author = request.user
		business.save()
		messages.success(requests, "Successfully Created!")
		return redirect("businesses:list")
	context = {
	"title": "Create",
	"form": form,
	}
	return render(request, "business_create.html", context)

def business_detail(request, business_slug):
	instance = get_object_or_404(Business, slug=business_slug)
	if instance.publish>timezone.now().date() or instance .draft:
		if not (request.user.is_staff or request.user.is_superuser):
			raise Http404
	if request.user.is_authenticated():
        if Like.objects.filter(post=instance, user=request.user).exists():
            liked = True
        else:
            liked = False
    business_like_count = instance.like_set.all().count()
	context = {
	"title":"Detail",
	"instance":instance,
	"share_string": quote(instance.content),
	"business_like_count":business_like_cout,
	"liked:liked,"
	}
	return render(request, "business_detail.html", context)

def business_list(request):
	today = timezone.now().date()
	query = request.GET.get("q")
	if query:
		object_list = object_list.filter(
			Q(title__icontains=query)|
			Q(content__icontains=query)|
			Q(author__first_name__icontains=query)|
			Q(author__last_name__icontains=query)
			).distinct()

	(draft=False).filter(publish__lte=today)
	if request.user.is_staff or request.user.is_superuser:
		object_list = Business.objects.all()

	query = request.GET.get("q")
	if query:
		object_list = object_list.filter(title__icontains=query)


	paginator = Paginator(object_list, 5) # Show 5 contacts per page
	page = request.GET.get('page')
	try:
		objects = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		objects = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		objects = paginator.page(paginator.num_pages)
	context = {
	"object_list": object_list,
	"title":"List",
	"user": request.user,
	"today": today,
	}
	return render(request, "business_list.html", context)

def business_update(request, business_slug):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	instance = get_object_or_404(Business, slug=business_slug)
	form = BusinessForm(request.BUSINESS or None, instance = instance)
	if form.is_valid():
		form.save()
		messages.success(request, "Successfully Edited!")
		return redirect(instance.get_absolute_url())
	context = {
	"form":form,
	"instance": instance,
	"title": "Update"
	}
	return render(request, "business_update.html", context)

def ajax_like(request, post_id):
    business_object = Business.objects.get(id=business_id)
    new_like, created = Like.objects.get_or_create(user=request.user, business=business_object)

    if created:
        action="like"
    else:
        new_like.delete()
        action="unlike"

    business_like_count = business_object.like_set.all().count()
    response = {
        "action": action,
    }
    return JsonResponse(response, safe=False)	

def business_delete(request, business_slug):
	instance = get_object_or_404(Business, slug=business_slug)
	instance.delete()
	messages.success(request, "Successfully Deleted!")
	return redirect("businesses:list")

def usersignup(request):
    context = {}
    form = UserSignup()
    context['form'] = form
    if request.method == 'BUSINESS':
        form = UserSignup(request.BUSINESS)
        if form.is_valid():
            user = form.save()
            username = user.username
            password = user.password

            user.set_password(password)
            user.save()

            auth_user = authenticate(username=username, password=password)
            login(request, auth_user)

            return redirect("businesses:list")
        messages.error(request, form.errors)
        return redirect("posts:signup")
    return render(request, 'signup.html', context)

    def userlogin(request):
    context = {}
    form = UserLogin()
    context['form'] = form
    if request.method == 'BUSINESS':
        form = UserLogin(request.BUSINESS)
        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            auth_user = authenticate(username=username, password=password)
            if auth_user is not None:
                login(request, auth_user)
                return redirect('businesses:list')

            messages.error(request, "Wrong username/password combination. Please try again.")
            return redirect("businesses:login")
        messages.error(request, form.errors)
        return redirect("businesses:login")
    return render(request, 'login.html', context)

    def userlogout(request):
    	logout(request)
    	return redirect("businesses:list")
	

# Create your views here.

businesses/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    {% block title %}

    {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

    {% include "messages.html" %}

    <div class="container">
        {% block content %}

        {% endblock content %}

    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
</script>        
</body>
</html>

businesses/templates/business_create.html
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Business {{title}}</title>
</head>
<body>
{% extends "base.html" %}

{% block title %}
	Create
{% endblock title %}

{% block content %}
	<h1>The Business {{title}} Page</h1>
	<form action="{% url 'businesses:create' %}" method="BUSINESS" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="Create Business">
	</form>	
</body>
</html>

businesses/templates/business_delete.html
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Business {{title}}</title>
</head>
<body>
	<h1>The Business {{title}} Page</h1>
</body>
</html>

businesses/templates/business_detail.html
{% extends "base.html" %}
{% load urlify %}

{% block title %}
{{title}}
{% endblock title %}

{% block content %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		{% if instance.image %}
			<img src="{{instance.image.url}}" alt="" class="img-responsive">
		{% endif %}
		<h1>{{instance.title}} <small>{{instance.timestamp}}</small></h1>
		{{instance.content| linebreaks}} <br>

		Author: {{instance.author.get_full_name}} <br>
		<a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
			Share on Facebook
		</a>

		<a href="https://twitter.com/home?status={{instance.content|truncatechars:35|urlify}}%20{{request.build_absolute_uri}}">
			Share on Twitter
		</a>

		<a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{instance.title|urlify}}&summary={{instance.content|truncatechars:35|urlify}}&source={{request.build_absolute_uri}}">
		Share on Linkedin
		</a>
		<br>
		{% include 'django_comments.html' %}
	</div>
</div>
{% endblock content %}

<button class="btn" onclick="ajax_like()">
    <span id="likes_count">{{ business_like_count }}</span>
    <span id= "heart" class="glyphicon glyphicon-heart {% if liked %}text-danger{% endif %}" aria-hidden="true"></span>
</button>

<script type="text/javascript">
    function ajax_like() {
        console.log("Like/Unlike clicked!");
        $.ajax(
            {
                type:'GET',
                url: '{% url "businesses:like_button" businesses_id=instance.id %}',
                error: function(){
                    console.log('error');
                },
                success: function(data){ 
                    $("#likes_count").text(data.post_like_count);

                    if(data.action==="like"){
                        $("#heart").addClass("text-danger");
                    }else{
                        $("#heart").removeClass("text-danger")  
                    }
                },
            }
        );
    }
</script>

businesses/templates/business_list.html
{% extends "base.html" %}
{% load urlify %}
{% block title %}
{{title}}
{% endblock title %}

{% block content %}

	<h1>{{title}}</h1>
	<div class="row">
	<form action="" method="GET">
	<input type="text" name='q' placeholder="Search posts" value="{{request.GET.q}}">
		<input type="submit" value="Search">
	</form>
	
	{% for object in object_list %}
		<div class="col-sm-6 col-sm-offset-3">
			<div class="thumbnail">
				{% if object.image %}
					<img src="{{object.image.url}}" alt="" class="img-responsive">
				{% endif %}
				<!--<img src="..." alt="...">-->
				<div class="caption">
					<h3><a href="{{ object.get_absolute_url }}">{{object.title}}</a><small> {{object.timestamp|timesince }} ago</small></h3>

					{% if object.draft %}<h3>Draft</h3>{% endif %}
					{% if object.publish > today %}<h3>Future Business</h3>{% endif %}

					<p>{{object.content|linebreaks|truncatechars:100}}</p>
					<p><a href="{{ object.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
				</div>
			</div>    
				<a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
		Share on Facebook
		</a>
		<br>

		<a href="https://twitter.com/home?status={{instance.content|truncatechars:35|urlify}}%20{{request.build_absolute_uri}}">
			Share on Twitter
		</a>
		<br>

		<a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{instance.title|urlify}}&summary={{instance.content|truncatechars:35|urlify}}&source={{request.build_absolute_uri}}">
		Share on Linkedin
		</a>
			</div>
		</div>

		

	{% endfor %}
	</div>
	<div class="pagination">
		<span class="step-links">
			{% if object_list.has_previous %}
				<a href="?page={{ object_list.previous_page_number }}">previous</a>
			{% endif %}

			<span class="current">
				Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
			</span>

			{% if object_list.has_next %}
				<a href="?page={{ object_list.next_page_number }}">next</a>
			{% endif %}
		</span>
	</div>
{% endblock content %}

businesses/templates/business_update.htm
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Business {{title}}</title>
</head>
<body>
	{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %}

	<h1>The Business {{title}} Page</h1>
	<form action="{% url 'businesses:update' business_slug=instance.slug %}" method="BUSINESS" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" name="Update Business">
	</form>	
</body>
</html>

businesses/templates/django_comments.html
{% load comments %}
{% get_comment_list for instance as comments %}

{% for comment in comments %}
	<div class="alert alert-info" role="alert"><b>{{ comment.user_name }} said:</b> {{ comment.comment|linebreaks}}</div>
{% endfor %}

{% get_comment_form for instance as form %}
<form action="{% comment_form_target %}" method="BUSINESS">
	{% csrf_token %}
	<input type="hidden" name="name" value="{{ request.user.username }}">
    <input type="hidden" name="email" value="{{ request.user.email }}">
    <input type="text" class="form-control input-lg" name="comment">
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="next" value="{{instance.get_absolute_url}}">
    <input type="submit" name="submit" class="btn btn-primary">

	<input type="submit" name="submit" class="btn btn-primary">
</form>		

businesses/templates/messages.html
{% if messages %}
<ul class='messages'>
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
    {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

businesses/templates/signup.html
{% extends "base.html" %}
{% block title %}
Sign Up
{% endblock title %}


{% block content %}
    <form action="{% url 'businesses:signup' %}" method="BUSINESS">
        {% csrf_token %}
        {{form.as_p}}
        <input class = "btn btn-primary" type="submit" value="Sign Up">
    </form>
{% endblock content %}